---
- hosts: localhost
  roles:
    - role: homebrew
      tags: homebrew
    - role: shell
      tags: shell
    - role: dotfiles
      tags: dotfiles
    - role: python
      tags: python
    - role: osx
      tags: osx

  tasks:
  - name: Set MOTD
    sudo: yes
    copy:
      src: files/motd
      dest: /etc/motd
      owner: nvandijk
      group: wheel
      mode: '644'
    tags:
      - motd
