---
- hosts: localhost
  tasks:
  - name: homebrew update
    homebrew: update_homebrew=yes
  - name: ensure homebrew packages
    homebrew: name={{ item }} state=latest
    with_items:
      - python
      - python3
      - ruby
      - git
      - mercurial
      - ssh-copy-id
      - zsh
  - name: ensure symlinks to dotfiles
    file: src={{ item.src }} dest={{ item.dest }} state=link
    with_items:
      - { src: '~/.dotfiles/zshrc.symlink', dest: '~/.zshrc' }
      - { src: '~/.dotfiles/gitconfig.symlink', dest: '~/.gitconfig' }
      - { src: '~/.dotfiles/gitignore.symlink', dest: '~/.gitignore' }
      - { src: '~/.dotfiles/hgrc.symlink', dest: '~/.hgrc' }
      - { src: '~/.dotfiles/hgignore.symlink', dest: '~/.hgignore_global' }
      - { src: '~/.dotfiles/opendiff-w', dest: '/usr/local/bin/opendiff-w' }
      - { src: '~/.dotfiles/Sublime\ Text/', dest: '~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User' }
      - { src: '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl', dest: '/usr/local/bin/subl' }
    tags:
      - symlinks
  - name: ensure global python packages
    pip: name={{ item }}
    with_items:
      - ipdb
      - ipython
      - virtualenv
      - virtualenvwrapper
      - mercurial_keyring
    tags:
      - python
  - name: ensure zsh is the default shell
    command: chsh -s /usr/local/bin/zsh
    tags:
      - shell
  - name: ensure osx defaults
    command: "{{ item }}"
    with_items:
      - sudo -v
      - sudo scutil --set ComputerName "quebec"
      - sudo scutil --set HostName "quebec"
      - sudo scutil --set LocalHostName "quebec"
      - sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "quebec"
      - chflags nohidden ~/Library
      - defaults write com.apple.DesktopViewSettings.IconViewSettings arrangeBy -string "name"
      - defaults write com.apple.DesktopViewSettings.IconViewSettings iconSize -int 64
      - defaults write com.apple.DesktopViewSettings.IconViewSettings gridSpacing -int 100
      - defaults write com.apple.DesktopViewSettings.IconViewSettings textSize -int 12
      - defaults write com.apple.DesktopViewSettings.IconViewSettings labelOnBottom -bool false
    tags:
      - osx
