#!/bin/bash

brew update
brew upgrade

brew install zsh
brew install tree
brew install git
brew install mercurial
brew install python
brew install python3
brew install ruby
brew install mysql
brew install postgresql
brew install jpeg
brew install ssh-copy-id

brew cleanup
