#!/bin/bash

brew update
brew upgrade

brew install z
brew install zsh
brew install wget
brew install git
brew install mercurial
brew install python
brew install python3
brew install ruby
brew install memcached
brew install node
brew install mysql
brew install postgresql
brew install redis
brew install jpeg
brew install ssh-copy-id
brew install gettext

brew cleanup
