---
- name: ensure oh my zsh repo is cloned
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: ensure zsh syntax highligthing repo is cloned
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.zsh-syntax-highlighting

- name: ensure zsh is available
  become: true
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/zsh
    state: present

- name: ensure zsh is the default shell
  command: chsh -s /usr/local/bin/zsh
