---
- name: ensure symlinks to dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '~/.dotfiles/dotfiles/zshrc.symlink', dest: '~/.zshrc' }
    - { src: '~/.dotfiles/dotfiles/gitconfig.symlink', dest: '~/.gitconfig' }
    - { src: '~/.dotfiles/dotfiles/gitignore.symlink', dest: '~/.gitignore' }
    - { src: '~/.dotfiles/dotfiles/hgrc.symlink', dest: '~/.hgrc' }
    - { src: '~/.dotfiles/dotfiles/hgignore.symlink', dest: '~/.hgignore_global' }
    - { src: '~/.dotfiles/extras/opendiff-w', dest: '/usr/local/bin/opendiff-w' }
    - { src: '~/.dotfiles/sublimetext/', dest: '~/Library/Application Support/Sublime Text 3/Packages/User' }
    - { src: '~/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl', dest: '/usr/local/bin/subl' }
