---
- name: homebrew update
  homebrew: update_homebrew=yes

- name: ensure homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew.packages }}"

- name: homebrew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.cask_packages }}"
