---
- name: homebrew update
  homebrew: update_homebrew=yes

- name: homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew.taps }}"

- name: homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew.packages }}"

- name: homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.cask_packages }}"
